### ISSUE TITLE
Any plans to publish to the Chrome Web Store?

### ISSUE THREAD

**Issue by HannesGitH** [yobibyte/ar5iv_chrome_ext#2]
[here](https://developer.chrome.com/docs/webstore/publish/) is how to do it (it costs $5 to create an official account tho)

Would be super nice and i'd use it

The hassle of cloning this repo and adding it in some kind of developer-mode for every instance of Chrome (since no cross-device sync of manually added extensions) is just to high for me to bother

If you don't want to do this i'd like to ask for your permission to create the corresponding official extension in the Chrome Store

**Comment by yobibyte** [comment]
Sure, go ahead!

**Comment by HannesGitH** [comment]
sadly its not as easy as i thought, since uploading now requires manifest v3..
but imma update it and open a PR then

**Comment by HannesGitH** [comment]
PR (#3) is opened btw @yobibyte
